### ISSUE TITLE
Is there a way to pipe into it?

### ISSUE THREAD

**Issue by BlackAsLight** [deno-library/compress#15]
I'm wondering if there is a way for me to send it pipe into it. By sending it individual strings and it compresses it all up. Instead of having to write it to a file then use the package to compress that file.

**Comment by fuxingZhang** [comment]
This feature is not currently available.

I haven't done JS and TS related development for a long time, and I don't have enough energy to do this.

**If you're willing to do this, I'm more than happy to merge your code.**

**Comment by BlackAsLight** [comment]
I could give it a shot

**Comment by BlackAsLight** [comment]
I couldn't figure out how to end up doing it.
