### ISSUE TITLE
Please update std/archive package to latest (0.213.0) version

### ISSUE THREAD

**Issue by MMMartt** [deno-library/compress#16]
Hello, I upgrade deno to 1.4.0 and found deno is complaining about this library.

And I found, in Deno 1.4.0 `Deno.FsFile.rid` and `Deno.close` are [marked as deprecated](https://github.com/denoland/deno/blob/9951506506ded805ff5eb09b52fb0235c0c3df79/Releases.md?plain=1#L32-L51), but this library is still using it.

And that come from "https://deno.land/std@0.129.0/archive/tar.ts" list in `deps.ts`, please upgrade the version.

**Comment by MMMartt** [comment]
#17 I opened a pr, only modify std/archive version.

**Comment by fuxingZhang** [comment]
Landed in [v0.4.6](https://github.com/deno-library/compress/releases/tag/v0.4.6)
