### ISSUE TITLE
NotFound: No such file or directory

### ISSUE THREAD

**Issue by squarepear** [deno-library/compress#4]
The `tar.uncompress()` function does not work because it attempts to write to a file that doesn't exist. I'll create a quick pull request once I find and fix the issue!

```
Check file:///Users/username/Downloads/test/mod.ts
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    throw new ErrorClass(res.err.message);
          ^
    at processResponse (deno:core/core.js:213:11)
    at Object.jsonOpAsync (deno:core/core.js:231:12)
    at async Object.open (deno:runtime/js/30_files.js:45:17)
    at async Module.uncompress (https://deno.land/x/compress@v0.3.6/tar/mod.ts:13:18)
```

**Comment by fuxingZhang** [comment]
### Sorry to see now

#### I tested and found no problems

**Comment by fuxingZhang** [comment]
## Sorry to see now

### I tested and found no problems  
Unit testing is Ok

![image](https://user-images.githubusercontent.com/25921552/113505203-e7ee6180-956f-11eb-8747-79e7512dc4ae.png)

![image](https://user-images.githubusercontent.com/25921552/113505207-ecb31580-956f-11eb-8a13-9f5ba86d1d41.png)

### Why the error occurred
> The tar.uncompress() function does not work because it attempts to write to a file that doesn't exist.  

The `tar.uncompress()` function to decompress a .tar file, so the written file must not exist.

![image](https://user-images.githubusercontent.com/25921552/113505461-8f1fc880-9571-11eb-8dce-ae8885df0710.png)

Can you provide a test case，like below (The following code is ok when I run)
```ts
import { tar } from "https://deno.land/x/compress@v0.3.6/mod.ts";
await tar.compress("./abc","./abc.tar");
await tar.uncompress("./abc.tar","./a");
```

**Comment by fuxingZhang** [comment]
## Sorry to see now

### I tested and found no problems  
Unit testing is Ok

![image](https://user-images.githubusercontent.com/25921552/113505203-e7ee6180-956f-11eb-8747-79e7512dc4ae.png)

![image](https://user-images.githubusercontent.com/25921552/113505207-ecb31580-956f-11eb-8a13-9f5ba86d1d41.png)

### Why the error occurred
> The tar.uncompress() function does not work because it attempts to write to a file that doesn't exist.  

The `tar.uncompress()` function to decompress a .tar file, so the written file must not exist.

![image](https://user-images.githubusercontent.com/25921552/113505461-8f1fc880-9571-11eb-8dce-ae8885df0710.png)

Can you provide a test case，like below (The following code is ok when I run)
```ts
import { tar } from "./mod.ts";
await tar.compress("./abc","./abc.tar");
await tar.uncompress("./abc.tar","./a");
```

**Comment by squarepear** [comment]
Hello! Your test case runs fine. I have the problem when uncompressing a tgz that uses the tar function. Sorry that I seem to have not mentioned that.

Here is a test case to show my problem. This is the .tgz I am using, but it also happens with others. I tested this in both macOS x64 and Linux aarch64 and had the same issue.
https://registry.npmjs.org/@types/p5/-/p5-0.9.1.tgz

## Doesn't work
```ts
import { tgz } from "https://deno.land/x/compress@v0.3.6/mod.ts";
await tgz.uncompress("./p5-0.9.1.tgz","./p5");
```

## Does work (My pull request)
```ts
import { tgz } from "https://raw.githubusercontent.com/SquarePear/compress/patch-1/mod.ts";
await tgz.uncompress("./p5-0.9.1.tgz","./p5");
```

I'm not sure why `create: true` isn't working?

Thanks for making this very cool module!

**Comment by fuxingZhang** [comment]
### Really a bug  
The error is reported because the parent folder of the file to be created does not exist
![image](https://user-images.githubusercontent.com/25921552/113512201-154e0600-9596-11eb-807f-2b2c73d0b601.png)

**Comment by fuxingZhang** [comment]
### Version updated to v0.3.7  
v0.3.6 => v0.3.7  
```ts
import { tgz } from "https://deno.land/x/compress@v0.3.7/mod.ts";
await tgz.uncompress("./p5-0.9.1.tgz","./p5");
```

**Comment by squarepear** [comment]
The new version works great! Thank you!
