### ISSUE TITLE
TS2322 [ERROR]: Type 'number' is not assignable to type 'Uint8Array'.

### ISSUE THREAD

**Issue by caucik** [deno-library/compress#6]
When running my project with this library included using deno 1.8.3 I get this error:
TS2322 [ERROR]: Type 'number' is not assignable to type 'Uint8Array'.
  if (readed === null) return readed;
    at https://deno.land/x/compress@v0.3.6/utils/uint8.ts:16:24

**Comment by fuxingZhang** [comment]
Please provide a test case.

**Comment by fuxingZhang** [comment]
Updated to v0.3.8, you can try again.
```ts
import { xxx } from "https://deno.land/x/compress@v0.3.8/mod.ts";
```

**Comment by caucik** [comment]
I am attaching the testcases.
[testcases.zip](https://github.com/deno-library/compress/files/6278644/testcases.zip)

**Comment by fuxingZhang** [comment]
Received, I will test it tomorrow

**Comment by fuxingZhang** [comment]
> I am attaching the testcases.
> [testcases.zip](https://github.com/deno-library/compress/files/6278644/testcases.zip)

testcases.zip does not contain code that can reproduce the error

**Comment by fuxingZhang** [comment]
The test case I said is the code that can reproduce the error
