### ISSUE TITLE
Large number of files problem duping compression

### ISSUE THREAD

**Issue by alkan** [deno-library/compress#8]
compress v0.3.9
deno v1.13.2

Thank you for your effort, very useful utility.

When I try to `tar.compress` or `tgz.compress` on a directory including several subdirs and 23289 files I got the following error:
Uncaught RangeError: Maximum call stack size exceeded
    at Tar.getReader (https://deno.land/std@0.104.0/archive/tar.ts:450:12)
    at Module.compress (https://deno.land/x/compress@v0.3.9/tar/mod.ts:79:23)

I did not change any V8 options.   Probably recursion is not suitable in this case.

**Comment by fuxingZhang** [comment]
Since I haven’t written typescript and js for a long time.
I used the simplest way to modify the code.
If you have a good idea, **I am very happy to merge your pull request.**

![image](https://user-images.githubusercontent.com/25921552/131500917-59ca41f1-e280-46e1-89d5-f80f9e9c986f.png)
